# Generated by Django 4.0 on 2021-12-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('publishedAt', models.DateTimeField()),
                ('thumbnail', models.URLField()),
                ('channelId', models.CharField(max_length=100)),
                ('channelTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('quotaFinished', models.BooleanField(default=False)),
            ],
        ),
    ]
